version: '3'
services:
  express:
    build:
      context: ./express
    networks:
      - phai-network
    ports:
      - "3300:3300"
    environment:
      - MONGO_URI=mongodb://mongodb:27017/mydatabase

  nginx:
    image: nginx
    networks:
      - phai-network
    ports:
      - "8000:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf

  mongodb:
    image: mongo
    networks:
      - phai-network
    ports:
      - "28017:28017"
    volumes:
      - mongodb-data:/data/db

networks:
  phai-network:
    driver: bridge

volumes:
  mongodb-data:

